Algoritmo "q01"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Exibindo os números existentes entre
// 1 e 100
Var
// Sistemas de declarações de variáveis
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibição dos números presentes entre 1 e 100")
contador <- 1
enquanto ( contador <= 100 )  faca
         escreval ( contador )
         contador <- contador + 1
fimenquanto

Fimalgoritmo