Algoritmo "semnome"
// Exibindo os quadrados dos inteiros existentes entre
// 15 e 200
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibição dos quadrados dos números inteiros existentes entre 15 e 200")
contador <- 15
enquanto ( contador <= 200 ) faca
         escreval ( contador, " x", contador, "=", contador * contador )
         contador <- contador + 1
fimenquanto
Fimalgoritmo