Algoritmo "semnome"
// Exibindo a soma dos cem primeiros valores a partir do 1
Var
// Seção de Declarações das variáveis 
contador ,nu: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("A soma dos cem primeiros valores é igual a:")
enquanto ( contador <= 100 ) faca
         nu <- nu + contador
         contador <- contador + 1
         escreval(nu)
fimenquanto
           escreval("A soma dos valores entre 1 e 100", nu)
Fimalgoritmo