Algoritmo "semnome"
// Faça uma tabela de multiplicação, de um número qualquer, até 10
Var
// Seção de Declarações das variáveis 
contador: inteiro
mul: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibindo tabela")
contador <- 2
enquanto ( mul <= 10 ) faca
         escreval( contador, " x", mul, " =", contador * mul )
         mul <- mul + 1
fimenquanto
Fimalgoritmo