Algoritmo "q15"
// 15)	Desenvolver um programa que apresente a série de Fibonacci até o
// décimo quinto termo. A série de Fibonacci é formada pela sequência
// 1,1,2,3,5,8,13,21,34, ... etc. Ela se caracteriza pela soma de um termo
// posterior com seu anterior subsequente
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo